### ISSUE TITLE
Auto discovery agents

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0core#51]
## What

- リソースを仮想化するサーバである `node/compute` のモデルを作成する
  - 将来的にはネットワーク機器として `node/network` を増やす #71 
- サーバにはひとつのプロセスを起動するだけでサービス提供が行うことができるようにする
- プロセスはMQに対してジョインの通知を行う
- 起動時のコマンドライン引数でどのターゲットをインポートするか選択する
- 現在のノードの状態を監視
- プロセスが死んでもサービスが続行できなければならない

## Why

- スケーラブルなサービスとして必要
- どんなクラウド基盤でも展開は多くの問題を抱えている

## モデル

`node/compute`

```yaml
id: 486274b2-49e4-4bcd-a60d-4f627ce8c041
type: node/compute
state: enum("JOINED", "LEAVED", "DELETED")  # LEAVED == DRAINED
name: hogehoge
suppoting_resource:
  - "resource/network/flat"
```

### ノードのジョイン

- aggregaterに通知
  - spec_idは生成

### コマンドライン

`n0core-node --name ... --mq-url ... --default-state JOINED --log...`

## 影響範囲

- `n0core.processor.agent` の `init` の処理と動的モジュール追加に関する実装
- `n0core.processor.distributor` のnodeに関する処理
- `n0core.model.node` 配下の作成

resolve #65 
relate to #69 
relate to #9 
relate to #2
