### ISSUE TITLE
Orchestration pipeline with n0api

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0core#77]
## what

- べき等な1連の操作をPipeline、VMの状態などのデータをmodelsとし、それを一塊にしたリクエストをspecとする
- プロビジョニングにPipelineの考えを導入する
  - stage: 時系列
  - step: 1 stage で実行するtask
  - task: 1つのモデルに対するべき等な操作 (VMではBootなど)
  - operation: Taskの中身 (BootではVMを作成・動作確認)
- Pipelineは将来的にn0stack全体に導入したい考えなので、n0coreではなくn0apiのような別コンポーネントを作る
  - よってn0coreには1回のリクエストにつき、1回のタスクを実行するようなAPIを作成する
  - pipelineはn0apiが責任を持ち、modelsは各コンポーネントが責任を持つ (本当か?)
- model.type は `(\w*)/(\w*)/(\w*)` となっており各値は以下の通りの意味を持つ
  - `$1` : modelの定義、どのコンポーネントが担当するかわかる
  - `$2` : modelの区分、実行できるTaskを区別する
  - `$3` : さらに細分化 Operationが定義される?
- messageの構成は以下の通りになる
  - task: n0core/api から各プロセスに指示を出す
  - notification: taskの進捗をaggregatorになげる
- repositoryには現在の最新のモデルをキャッシュしておくだけでよい

## why

- pipelineを導入することによって進捗及び、バグフィクスをしやすくする
- べき等を突き詰めることで高信頼性のインフラを提供する

### n0core

```
specID:
task_id:
task: Boot
model_id: [vm_id]
models:
  - type: resource/vm/...
    name: hoge
```

### n0api

```
specID:
models:
  - type: resource/vm/...
    name: hoge
pipeline:
  schedule:
    schedule_all_about_hoge:
      task: Schedule
      id: [vm_id]
  deploy:  
    boot_hoge:
      task: Boot
      id: [vm_id]
  loadbalance:
    add_instance:
      task: Target
      id: [lb_id]
```
